#!/usr/bin/env node

/**
 * AIQA Setup Script
 * 
 * Interactive setup wizard for first-time configuration
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import readline from 'readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function main() {
  console.log(`
╔════════════════════════════════════════════════════════════════╗
║                     AIQA Setup Wizard                          ║
╠════════════════════════════════════════════════════════════════╣
║                                                                ║
║  Welcome to AIQA! Let's get you set up.                       ║
║                                                                ║
╚════════════════════════════════════════════════════════════════╝
`);

  // Check if .env already exists
  const envPath = path.join(__dirname, '.env');
  let envExists = false;
  
  try {
    await fs.access(envPath);
    envExists = true;
    console.log('⚠️  .env file already exists.');
    const overwrite = await question('Do you want to reconfigure? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled. Existing configuration preserved.');
      rl.close();
      return;
    }
  } catch {
    // .env doesn't exist, continue with setup
  }

  console.log('\n📝 Configuration\n');
  
  // Get LLM provider
  console.log('Select LLM Provider:');
  console.log('  1. OpenAI (GPT-4)');
  console.log('  2. Anthropic (Claude)');
  const providerChoice = await question('\nChoice (1 or 2) [default: 1]: ') || '1';
  
  const provider = providerChoice === '2' ? 'anthropic' : 'openai';
  
  // Get API key
  const apiKeyName = provider === 'openai' ? 'OPENAI_API_KEY' : 'ANTHROPIC_API_KEY';
  console.log(`\n🔑 ${provider === 'openai' ? 'OpenAI' : 'Anthropic'} API Key`);
  console.log('   Get your key from:');
  console.log(`   ${provider === 'openai' ? 'https://platform.openai.com/api-keys' : 'https://console.anthropic.com/settings/keys'}`);
  
  const apiKey = await question(`\nEnter your ${provider === 'openai' ? 'OpenAI' : 'Anthropic'} API key: `);
  
  if (!apiKey || apiKey === 'your_openai_api_key_here' || apiKey === 'your_anthropic_api_key_here') {
    console.log('\n❌ Invalid API key. Setup cancelled.');
    console.log('Please run setup again with a valid API key.');
    rl.close();
    return;
  }
  
  // Get server port
  const port = await question('\n🌐 Server port [default: 3000]: ') || '3000';
  
  // Create .env file
  let envContent = `# AIQA Configuration
# Generated by setup wizard on ${new Date().toISOString()}

# LLM Configuration
`;
  
  if (provider === 'openai') {
    envContent += `OPENAI_API_KEY=${apiKey}\n\n`;
    envContent += `# Anthropic Configuration (Optional)\n`;
    envContent += `# ANTHROPIC_API_KEY=your_anthropic_api_key_here\n\n`;
  } else {
    envContent += `# OPENAI_API_KEY=your_openai_api_key_here\n\n`;
    envContent += `ANTHROPIC_API_KEY=${apiKey}\n\n`;
  }
  
  envContent += `# Server Configuration
PORT=${port}
HOST=localhost

# Environment
NODE_ENV=development
`;

  await fs.writeFile(envPath, envContent);
  console.log('\n✅ .env file created successfully!');
  
  // Update config.json
  const configPath = path.join(__dirname, 'config.json');
  const configContent = await fs.readFile(configPath, 'utf8');
  const config = JSON.parse(configContent);
  
  config.llm.provider = provider;
  if (provider === 'anthropic') {
    config.llm.model = 'claude-3-sonnet-20240229';
  }
  
  await fs.writeFile(configPath, JSON.stringify(config, null, 2));
  console.log('✅ config.json updated with your preferences!');
  
  // Create necessary directories
  console.log('\n📁 Creating directories...');
  const dirs = ['logs', 'logs/ai_interactions', 'reports', 'plans', 'artifacts', 'testcases/uploaded'];
  
  for (const dir of dirs) {
    const dirPath = path.join(__dirname, dir);
    try {
      await fs.mkdir(dirPath, { recursive: true });
      console.log(`   ✓ ${dir}`);
    } catch (error) {
      console.log(`   ⚠️  ${dir} (may already exist)`);
    }
  }
  
  console.log('\n🎉 Setup complete!\n');
  console.log('Next steps:');
  console.log('  1. Install dependencies: npm install');
  console.log('  2. Install Playwright browsers: npx playwright install chromium');
  console.log('  3. Start the server: npm start');
  console.log('  4. Open your browser: http://localhost:' + port);
  console.log('\nFor CLI usage:');
  console.log('  node backend/executor/runner.js testcases/example_login.txt\n');
  
  rl.close();
}

main().catch(error => {
  console.error('\n❌ Setup failed:', error.message);
  rl.close();
  process.exit(1);
});

